sudo: false
dist: trusty
language: php

php:
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - github_token:
        secure: "sMGv0/C89ixk39sWFJHiPRv1L9XOkGeQ5Ecw2unZ2xRQcwg5aZtD8Vx4gRy2hSER8Tkr/CjvgFdRUx4CDZVG3kS761j0cLfAvmSAfhZViGnBIh9FNzB2kRIS/fzpCq9577u60kUmt6WPMYtDJgDrotIBuP11AewrJJsgKRQbGGyJ0uxfPpOK+r+5KcoJdeAN6RsYX2vkgO7fbCF8tGOo1FhTBMAyn6oMn2jGEV4S3M63zAG2xc+UHSSTyK4O0XeAdYccHLjZDPYbrhzB1MGsmJy52fggkKg6v+h/lgoNBzPbcQCg+H+1aGiZ1OXf2Gnzk6ksIjG2PXt3cgz3gy04gKIenTtnX+H34ex1RdF+oG+1pJVIw4qLx5JYv7CfI1CJNEHDqi1scf2l6B+qvd2MoELng0MDam0PgonnnPiyCdGcRst7G+h00ayLWaCAJ6grcpcmHEx85dpUe24nfdMkbTbmWaZaO3TcWgk+9bThKTzd9eRTAlfk6bvwZbX2TBBT1vUaJ+9/VODDm7omhoYKCgZg+d4HVlJF1Q4hHCyQhna/nDJ46g5FlT44Xd+otb464j2r5K1rJ0Irv1Xp7qRRHLR/xDwUILLHswZnOSYkFTr+c/AfVhKpek/vJN4w6UquTHXjX2N4jKNTELXtcnJZnw5xLs6Z0XH7br8K2GUE9AU="


install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - composer cs-check

after_script:
  - travis_retry composer upload-coverage
  - bash .bin/generate-tag.sh

before_deploy:
  - bash .bin/generate-release-package.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: NNe7dKhfEjPOW3sMUdGk7AD+l7Z9uonBLPZsV2uV+cdeiWoYlEvyBBhjGEHuFNdPBJENaofF7dkRDxaYrI2nIHAQCv539AuvDwfY1Q75iLskUOlvGfe35Bwu/cpZsW6o26PIV+UEpy3wmZvuIiHeF68n9pWXo3Tv6NS+iRt/nC7Wd3meEQZZyKuKaTieKa53bIop1P3bb0yYWb6PpEzOZb4P98F7tmHV8dcHVTUF7XtFsbmmGfByVuNp6ancrcwWELUJ6TpWTUAxAWlGAaKA3BkMKdsN6de+uHM+AF+G8m9s2kR5XWF/33N0tW6lAH6t91F/iG9go9q+ovlhjZRzodXSD04uV4w+S1CSSpFRTM4gKSvW8TxYVhL/YQNhJwb1qw3M5wKoqFMJcw0Zt0tpUFuy2pF8AzCjSIA0O1X4IWviB8TS7bAYtg85GaCGQ9MOPLo7eVu2o3vtCCQgoQjOZ8WLXDGOtCyR4nViJtDGKdZEsJxy4twELZFe0QwiZaVcGWijaCL6SpGfc2FD3dAJo3P9iyIZ4Q56yAfOmN6rIVjNp7mp6yym84lu66E2BsR/cVb7oipb4dBKjN5tk5KaabFgAoc+Low9Xmpg7ntuc92qUr9Vj2NhFJmmXMXRcjBDJC/7WQUgrQk4a6CIefkL0ond0dn6E0yc/3L8eW054v8=
  file: opencart-ee.ocmod.zip
  skip_cleanup: true
  on:
    repo: wirecard/opencart-ee
    tags: true

notifications:
  email: false
  slack:
    rooms:
      secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: change
