sudo: false
dist: trusty
language: php

cache:
  directories:
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "wirecard"
    token:
      secure: "sqilnMXDrk/XQOv3he/+9MBAfFWf53nPT+TewTp/A0tg96dcDIqFZhBreWyWEGFvLxR5BsybRJfz2HWx7LoXPG7Tl0CieH0ezqEMMXOp2Q0dmrNybzfyqNoeiSLWiaGW1Mq5zSuarfKGHyZb77WhieY0+Mdal4IkVG0nV+ThJmHVoVD3+lGUUN4SlK5MRgWnCLBv+erZ8jKVt19cBfYLI3FE7he/2YZVtd3Ml1/fK5S5Aj+4IOlgAztG8nhtjm1Robid/DN9NikvDFKRNilMrBfTzLiOWKZ5JatKyXY5JrTZu706ARv/n9J4NWHWjUsYylp/ZcZrS/Aq6qGYo5mSXvlBACIdTHjWEr7+vYIF+Mbsf5qQUKIfdTbIbdlsqfh7PfeqmZOiZUJiWhDZhNwGlnxyjaS8/olVFD5R6/CtV6aCD1RvSQBtyQIZ98rxvgO11CdO75/vrNnY9uZNIeYdaVyKci9d1kGRM1bbygdJXtmG678lQx4rulxStcOgM4UVZ3TsuAOBRmnkyM3lN12xGfKKiTb9PivUCmplYw8XdRjXaTlCLiWMQNGDQ2niwAdjicogWgEA7ZUGhM5W419MSv+csPPuHySWWwmmqOgVCJe8haY4GxmN1CiS249Ig6Tcc5HXVkvxlZ6vtkFjgYxCS0sipHtnw4Lxyh1k4rv0FuM="
    github_token:
      secure: "sMGv0/C89ixk39sWFJHiPRv1L9XOkGeQ5Ecw2unZ2xRQcwg5aZtD8Vx4gRy2hSER8Tkr/CjvgFdRUx4CDZVG3kS761j0cLfAvmSAfhZViGnBIh9FNzB2kRIS/fzpCq9577u60kUmt6WPMYtDJgDrotIBuP11AewrJJsgKRQbGGyJ0uxfPpOK+r+5KcoJdeAN6RsYX2vkgO7fbCF8tGOo1FhTBMAyn6oMn2jGEV4S3M63zAG2xc+UHSSTyK4O0XeAdYccHLjZDPYbrhzB1MGsmJy52fggkKg6v+h/lgoNBzPbcQCg+H+1aGiZ1OXf2Gnzk6ksIjG2PXt3cgz3gy04gKIenTtnX+H34ex1RdF+oG+1pJVIw4qLx5JYv7CfI1CJNEHDqi1scf2l6B+qvd2MoELng0MDam0PgonnnPiyCdGcRst7G+h00ayLWaCAJ6grcpcmHEx85dpUe24nfdMkbTbmWaZaO3TcWgk+9bThKTzd9eRTAlfk6bvwZbX2TBBT1vUaJ+9/VODDm7omhoYKCgZg+d4HVlJF1Q4hHCyQhna/nDJ46g5FlT44Xd+otb464j2r5K1rJ0Irv1Xp7qRRHLR/xDwUILLHswZnOSYkFTr+c/AfVhKpek/vJN4w6UquTHXjX2N4jKNTELXtcnJZnw5xLs6Z0XH7br8K2GUE9AU="

php:
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer cs-check
  - sonar-scanner --debug