sudo: false
dist: trusty
language: php

cache:
  directories:
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "wirecard"
    token:
      secure: "k328VRCpxurY/qXyuTdRTmBwF0JsvMVzlrV5RZEg6f2XxWN8yU0ZHhyWqhH3FhZZDh2K4Ui5OUpMRPx5jnXYu2GzauBHDN0KzF773OWB3ljyrWDBcH+iBP0Y+HxYLrToQXaurlMfc0IfZE+TDB2G2Ly8ZRdV/1WUONWS9beQQA0Ymv+aFOb+H6aVNOiv6mKgRERBpUyG7FDfBnkIPkZO8RLVnG6g57YfjVZKID5oq4dYuKWVEBkZZthrUaBQ3OzFkH2V1WKV4+kSnynm7Xj6kWd16P9XXEoLvH+X3ZFEtNbeVVWtRQ0rgUZE6dTGv8VtD7WfgiliyabmEJeoK77hDInQb2jLwZFlEUNZHYQ+VioAEyKKSQ5L4Fd+hef7y2flfemKYYNkVQK5pqDko0a7nU5hRvacq8+WQ5t2n8sGEzr4ySTKLXH6d72tcPnngqXzGole1+RRSF5yGNyDTs+HD5l1H4qmupLaIyRjXgLG7DHLeXu0j3+SOlfi85yKfVxLNJls0McSKouorndKPoxaUyCvXWYOIDby6QUfwnOZrgX8wHZ1F0Pe8n2KDwUJ32XSloiw1zF1I/7ObIACYr2PgZ3szS4s5bCdJ4e0Vw+Dq8etpcRsQcv1ln8EvC76Lut03KsuIiZhr7eY5gyrSUXSKXUMiv9J0EYjNsktljizwiA="
    github_token:
      secure: "sMGv0/C89ixk39sWFJHiPRv1L9XOkGeQ5Ecw2unZ2xRQcwg5aZtD8Vx4gRy2hSER8Tkr/CjvgFdRUx4CDZVG3kS761j0cLfAvmSAfhZViGnBIh9FNzB2kRIS/fzpCq9577u60kUmt6WPMYtDJgDrotIBuP11AewrJJsgKRQbGGyJ0uxfPpOK+r+5KcoJdeAN6RsYX2vkgO7fbCF8tGOo1FhTBMAyn6oMn2jGEV4S3M63zAG2xc+UHSSTyK4O0XeAdYccHLjZDPYbrhzB1MGsmJy52fggkKg6v+h/lgoNBzPbcQCg+H+1aGiZ1OXf2Gnzk6ksIjG2PXt3cgz3gy04gKIenTtnX+H34ex1RdF+oG+1pJVIw4qLx5JYv7CfI1CJNEHDqi1scf2l6B+qvd2MoELng0MDam0PgonnnPiyCdGcRst7G+h00ayLWaCAJ6grcpcmHEx85dpUe24nfdMkbTbmWaZaO3TcWgk+9bThKTzd9eRTAlfk6bvwZbX2TBBT1vUaJ+9/VODDm7omhoYKCgZg+d4HVlJF1Q4hHCyQhna/nDJ46g5FlT44Xd+otb464j2r5K1rJ0Irv1Xp7qRRHLR/xDwUILLHswZnOSYkFTr+c/AfVhKpek/vJN4w6UquTHXjX2N4jKNTELXtcnJZnw5xLs6Z0XH7br8K2GUE9AU="

php:
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - sonar-scanner
  - composer cs-check
