sudo: false
dist: trusty
language: php

cache:
  directories:
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "wirecard"

php:
  - 7.1
  - 7.0
  - 5.6

env:
  global:
    - secure: ${SONAR_TOKEN}
    - COMPOSER_ARGS="--no-interaction"
    - github_token:
        secure: "sMGv0/C89ixk39sWFJHiPRv1L9XOkGeQ5Ecw2unZ2xRQcwg5aZtD8Vx4gRy2hSER8Tkr/CjvgFdRUx4CDZVG3kS761j0cLfAvmSAfhZViGnBIh9FNzB2kRIS/fzpCq9577u60kUmt6WPMYtDJgDrotIBuP11AewrJJsgKRQbGGyJ0uxfPpOK+r+5KcoJdeAN6RsYX2vkgO7fbCF8tGOo1FhTBMAyn6oMn2jGEV4S3M63zAG2xc+UHSSTyK4O0XeAdYccHLjZDPYbrhzB1MGsmJy52fggkKg6v+h/lgoNBzPbcQCg+H+1aGiZ1OXf2Gnzk6ksIjG2PXt3cgz3gy04gKIenTtnX+H34ex1RdF+oG+1pJVIw4qLx5JYv7CfI1CJNEHDqi1scf2l6B+qvd2MoELng0MDam0PgonnnPiyCdGcRst7G+h00ayLWaCAJ6grcpcmHEx85dpUe24nfdMkbTbmWaZaO3TcWgk+9bThKTzd9eRTAlfk6bvwZbX2TBBT1vUaJ+9/VODDm7omhoYKCgZg+d4HVlJF1Q4hHCyQhna/nDJ46g5FlT44Xd+otb464j2r5K1rJ0Irv1Xp7qRRHLR/xDwUILLHswZnOSYkFTr+c/AfVhKpek/vJN4w6UquTHXjX2N4jKNTELXtcnJZnw5xLs6Z0XH7br8K2GUE9AU="


install:
  - travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - sonar-scanner
  - composer cs-check

after_script:
  - travis_retry composer upload-coverage
